name: Dev to SIT promotion pipeline

on:
  push:
    tags:
      t-*
  release:
    types:
      - created
  
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/@v1
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@v1


  run-pipeline:
    needs: tagname
    name: Get the tag version
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - id: step2
        run: echo "The tag name is ${{ steps.step1.output.VERSION }}"