name: Dev to SIT promotion pipeline

on:
  push:
    tags:
      - 't-*''
  release:
    types:
      - created
  
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/@v1
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@v1


  run-pipeline:
    needs: tagname
    runs-on: ubuntu-latest
    shell: bash
    steps:
      - name: Get Tag Name
        id: release_info
        run: |
          echo "::set-env name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//})"
