name: Dev to SIT promotion pipeline

on:
  push:
    tags:
      t-*
  release:
    types:
      - created
  
jobs:
  tagname:
    name: Check tag name conflict
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/@v1
      - name: help tag check
        uses: tsuyoshicho/action-vimhelp-tagname-check@v1


  tagname:
    name: Get the version
    id: get_version
    run: |
      echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//} \
      echo "The tag name is ${{ steps.get_version.output.VERSION }}"