name: Development And Unit Test Pipeline

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

jobs:
  build-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
    
    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -e .

      - name: Deploy integration test
        run: |
          dbx deploy --jobs=job1 --files-only

      - name: Run integration test
        run: |
          dbx launch --job=job1 --as-run-submit --trace

#      - name: Run unit tests
#        run: |
#          echo "Launching unit tests"
#          pytest tests/unit
      