name: Dev to SIT promotion pipeline

on:
  push:
    tags:
      t-*
  release:
    types:
      - created
  
jobs:
  get-tag:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}